<h1>Procurar Id</h1>

<?php
$id = $form->get('id');
$id->setAttribute('class', 'form-control');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('post', ['action' => 'procurarid']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($id); ?>
    <?= $this->formElement($id); ?>
</div>

<p>
<?php
echo $this->formSubmit($submit);
?>
</p>
<p>
<a class="btn btn-primary" href="<?= $this->url('post', ['action' => 'index']);?>">Tela Inicial</a>
</p>
<?php
echo $this->form()->closeTag();//Vai dar um barra em nosso form, vai fechar o nosso form
?>
